-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- ************************************** Sequence_12
CREATE SEQUENCE Sequence_12
START WITH 1
INCREMENT BY 1;
