-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- **************************************  Tag_12
CREATE TAG Tag_12;
