-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- **************************************  Tag_1
CREATE TAG Tag_1;
