-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *


-- **************************************  Tag_12
CREATE TAG Tag_12;

-- ************************************** Sequence_12
CREATE SEQUENCE Sequence_12
START WITH 1
INCREMENT BY 1;

CREATE FILE FORMAT FileFormat_2;

-- ************************************** table_32
CREATE TABLE table_32
(

);

-- ************************************** table_222
CREATE TABLE table_222
(

);

-- ************************************** Atable_1442
CREATE TABLE Atable_1442
(

);

-- ************************************** view_22
CREATE VIEW view_22

  Comment = 'No Comment Provided'

AS
(
  -- Please type view definition here

);

-- ************************************** view_12
CREATE VIEW view_12

  Comment = 'No Comment Provided'

AS
(
  -- Please type view definition here

);

-- ************************************** function_12
CREATE FUNCTION function_12()
Returns -- Please specify return type
Language -- Please specify function language

  Comment = 'No Comment Provided'

AS
'-- Please provide function definition'
;

-- ************************************** function2
CREATE FUNCTION function2()
Returns -- Please specify return type
Language -- Please specify function language

  Comment = 'No Comment Provided'

AS
'-- Please provide function definition'
;

-- ************************************** procedure_12
CREATE PROCEDURE procedure_12()
  Returns string -- Please specify return type
  Language Javascript
  Comment = 'No Comment Provided'

AS
$$
  // Please type procedure definition
$$;

-- ************************************** procedure2
CREATE PROCEDURE procedure2()
  Returns string -- Please specify return type
  Language Javascript
  Comment = 'No Comment Provided'

AS
$$
  // Please type procedure definition
$$;

