-- ************************************ SqlDBM: Snowflake ***********************************
-- * Generated by SqlDBM: Bug 35379 EV by anton.rassolenko+enterpriseplus_owner1@sqldbm.com *


-- ************************************** testtable
CREATE TABLE testtable
(

);

