-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- ************************************** function
CREATE FUNCTION function()
Returns -- Please specify return type
Language -- Please specify function language

  Comment = 'No Comment Provided'

AS
'-- Please provide function definition'
;
