-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- ************************************** Sequence_1
CREATE SEQUENCE Sequence_1
START WITH 1
INCREMENT BY 1;
