-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- ************************************** table_3
CREATE TABLE table_3
(

);
