-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *


-- **************************************  Tag_1
CREATE TAG Tag_1;

-- ************************************** Sequence_1
CREATE SEQUENCE Sequence_1
START WITH 1
INCREMENT BY 1;

CREATE FILE FORMAT FileFormat_1;

-- ************************************** table_2
CREATE TABLE table_2
(

);

-- ************************************** Atable_1441
CREATE TABLE Atable_1441
(

);

-- ************************************** view_1
CREATE VIEW view_1

  Comment = 'No Comment Provided'

AS
(
  -- Please type view definition here

);

-- ************************************** function
CREATE FUNCTION function()
Returns -- Please specify return type
Language -- Please specify function language

  Comment = 'No Comment Provided'

AS
'-- Please provide function definition'
;

-- ************************************** procedure
CREATE PROCEDURE procedure()
  Returns string -- Please specify return type
  Language Javascript
  Comment = 'No Comment Provided'

AS
$$
  // Please type procedure definition
$$;

