-- ********************************** SqlDBM: Snowflake **********************************
-- * Generated by SqlDBM: test246 PLEASE DON'T EDIT by Lesya.rylova+confluence@gmail.com *

-- ************************************** view_2
CREATE VIEW view_2

  Comment = 'No Comment Provided'

AS
(
  -- Please type view definition here

);
