-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: test246 by Lesya.rylova+confluence@gmail.com *

-- ************************************** Atable_1441
CREATE TABLE Atable_1441
(

);
