-- ************************** SqlDBM: Snowflake *************************
-- ** Generated by SqlDBM: test246 by Lesya.rylova+confluence@gmail.com *


-- ************************************** table_1
CREATE TABLE table_1
(

);
